### ISSUE TITLE
Create structuration pipelines

### ISSUE THREAD

**Issue by Lazzzer** [Lazzzer/structurizer#14]
### Description

**As a *user***, **I would like to** have pipelines guiding me through the whole structured data extraction process **so** I can make change in any steps and improve the final extraction.

### Acceptance criteria

- [x] The following pipelines should be available : upload, text recognition, data extraction and verification.
- [x] The user can stop at any pipeline and resume easily the process.
- [x] The pipelines provides all the necessary tools and informations to the user.

### Requirements
- #4 
- #5 
- #12 
- #13
